#!/bin/bash

filename="100k-most-used-passwords-NIST.txt"
output_hash="hashes.txt"
#password_hash='$6$xgLS35S6$2UjEq.dUhICPw9zgDVJXcQYQp/9ilLPQt/8Zgu0uwngI5mVvB1eKQG9SnVLjmOOfkB4Jjb5VSAXGXjY4Cf5k90'
#password_hash='$6$2Ff.cblr$QwoNFOAme5xy5/anjAsZVIDrZdBKZ.hZ6UIIdLU9D4DDEs3O.CbRsICaVxxdQOTG2TOHYSHDwfdsrG0WGsXVB/'
password_hash='$6$zZKc4nOX$Rac9mB17TLeFgE/TOH0gTgRnAmaNk67ezuZo4fQAOSkulEKrrW6sum0uElLvmAeBqhf0k/jCYn2dddJCC0QzI1'
#password_hash=''
#password_hash=''

 > "$output_hash"

while IFS= read -r line
do
        #hash=$(openssl passwd -6 -salt xgLS35S6 $line)
        hash=$(openssl passwd -6 -salt zZKc4nOX $line)
        #hash=$(openssl passwd -6 -salt 2Ff.cblr $line)
        #hash=$(openssl passwd -6 -salt 2Ff.cblr $line)
        #echo "$line $hash"
        #echo "$hash" >> "$output_hash"
        echo $hash
        #echo $password_hash

        if [ "$hash" = "$password_hash" ]; then
                #output_hash="$line"
                echo "$line" >> "$output_hash"
		break
        fi

done < "$filename"

